# Customizations for rubocop

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 30

Metrics/BlockNesting:
  Max: 5

# Relax of rules for phase 2
# see - https://github.com/bbatsov/rubocop/blob/master/config/enabled.yml
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/Documentation:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
Lint/Eval:
  Enabled: false
Style/BlockComments:
  Enabled: false
Style/WordArray: # requires %w() for arrays of words
  Enabled: false
